In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.],
           [89., 91., 90.], [96., 98., 100.], [73., 66., 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(1001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22655.951 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [22.293005]
 [18.633902]]
10 Cost:  6.041753 
Prediction:
 [[155.17455]
 [181.64264]
 [181.76219]
 [193.98837]
 [140.6934 ]]
20 Cost:  5.813164 
Prediction:
 [[155.56952]
 [182.1321 ]
 [182.23676]
 [194.50674]
 [141.06909]]
30 Cost:  5.7920403 
Prediction:
 [[155.56291]
 [182.13885]
 [182.23573]
 [194.50717]
 [141.0766 ]]
40 Cost:  5.7710066 
Prediction:
 [[155.55511]
 [182.14413]
 [182.23325]
 [194.50604]
 [141.08298]]
50 Cost:  5.7501135 
Prediction:
 [[155.54735]
 [182.1494 ]
 [182.23079]
 [194.50493]
 [141.08934]]
60 Cost:  5.7293425 
Prediction:
 [[155.53958]
 [182.15462]
 [182.2283 ]
 [194.50377]
 [141.09566]]
70 Cost:  5.7086334 
Prediction:
 [[155.53186]
 [182.15988]
 [182.22586]
 [194.50269]
 [141.10197]]
80 Cost:  5.688061 
Prediction:
 [[155.52414]
 [182.1651 ]
 [182.22343]
 [194.50157]
 [141.10829]]
90 Cost:  5.6675863 
Prediction:
 [[155.51643]
 [182.1703 ]
 [182.22098]
 [194.50044]
 [141.11455]]
100 